//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.19 at 08:25:00 AM GMT 
//


package jaxbClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="documentinfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="default">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="backgroundcolor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="font" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fontsize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fontcolor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="linecolor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fillcolor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="slide">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="text">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="b" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="i" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="u" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="font" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="fontsize" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="fontcolor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="xstart" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="ystart" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="xend" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="yend" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="linecolor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="shape">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="point">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="totalpoints" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="fillcolor" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="linecolor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="branch" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="audio">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="loop" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="image">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="urlname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="xstart" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="ystart" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="branch" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="video">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="loop" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="xstart" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="ystart" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="playtime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="lastslide" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentinfo",
    "_default",
    "slide"
})
@XmlRootElement(name = "slideshow")
public class jaxbSlideshow {

    @XmlElement(required = true)
    protected jaxbSlideshow.Documentinfo documentinfo;
    @XmlElement(name = "default", required = true)
    protected jaxbSlideshow.Default _default;
    @XmlElement(required = true)
    protected jaxbSlideshow.Slide slide;

    /**
     * Gets the value of the documentinfo property.
     * 
     * @return
     *     possible object is
     *     {@link jaxbSlideshow.Documentinfo }
     *     
     */
    public jaxbSlideshow.Documentinfo getDocumentinfo() {
        return documentinfo;
    }

    /**
     * Sets the value of the documentinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link jaxbSlideshow.Documentinfo }
     *     
     */
    public void setDocumentinfo(jaxbSlideshow.Documentinfo value) {
        this.documentinfo = value;
    }

    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link jaxbSlideshow.Default }
     *     
     */
    public jaxbSlideshow.Default getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link jaxbSlideshow.Default }
     *     
     */
    public void setDefault(jaxbSlideshow.Default value) {
        this._default = value;
    }

    /**
     * Gets the value of the slide property.
     * 
     * @return
     *     possible object is
     *     {@link jaxbSlideshow.Slide }
     *     
     */
    public jaxbSlideshow.Slide getSlide() {
        return slide;
    }

    /**
     * Sets the value of the slide property.
     * 
     * @param value
     *     allowed object is
     *     {@link jaxbSlideshow.Slide }
     *     
     */
    public void setSlide(jaxbSlideshow.Slide value) {
        this.slide = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="backgroundcolor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="font" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fontsize" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fontcolor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="linecolor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fillcolor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "backgroundcolor",
        "font",
        "fontsize",
        "fontcolor",
        "linecolor",
        "fillcolor"
    })
    public static class Default {

        @XmlElement(required = true)
        protected String backgroundcolor;
        @XmlElement(required = true)
        protected String font;
        @XmlElement(required = true)
        protected String fontsize;
        @XmlElement(required = true)
        protected String fontcolor;
        @XmlElement(required = true)
        protected String linecolor;
        @XmlElement(required = true)
        protected String fillcolor;

        /**
         * Gets the value of the backgroundcolor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBackgroundcolor() {
            return backgroundcolor;
        }

        /**
         * Sets the value of the backgroundcolor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBackgroundcolor(String value) {
            this.backgroundcolor = value;
        }

        /**
         * Gets the value of the font property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFont() {
            return font;
        }

        /**
         * Sets the value of the font property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFont(String value) {
            this.font = value;
        }

        /**
         * Gets the value of the fontsize property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFontsize() {
            return fontsize;
        }

        /**
         * Sets the value of the fontsize property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFontsize(String value) {
            this.fontsize = value;
        }

        /**
         * Gets the value of the fontcolor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFontcolor() {
            return fontcolor;
        }

        /**
         * Sets the value of the fontcolor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFontcolor(String value) {
            this.fontcolor = value;
        }

        /**
         * Gets the value of the linecolor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLinecolor() {
            return linecolor;
        }

        /**
         * Sets the value of the linecolor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLinecolor(String value) {
            this.linecolor = value;
        }

        /**
         * Gets the value of the fillcolor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFillcolor() {
            return fillcolor;
        }

        /**
         * Sets the value of the fillcolor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFillcolor(String value) {
            this.fillcolor = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "author",
        "version",
        "comment",
        "width",
        "height"
    })
    public static class Documentinfo {

        @XmlElement(required = true)
        protected String author;
        @XmlElement(required = true)
        protected String version;
        @XmlElement(required = true)
        protected String comment;
        protected int width;
        @XmlElement(name = "Height")
        protected int height;

        /**
         * Gets the value of the author property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthor() {
            return author;
        }

        /**
         * Sets the value of the author property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthor(String value) {
            this.author = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the comment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComment() {
            return comment;
        }

        /**
         * Sets the value of the comment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComment(String value) {
            this.comment = value;
        }

        /**
         * Gets the value of the width property.
         * 
         */
        public int getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         */
        public void setWidth(int value) {
            this.width = value;
        }

        /**
         * Gets the value of the height property.
         * 
         */
        public int getHeight() {
            return height;
        }

        /**
         * Sets the value of the height property.
         * 
         */
        public void setHeight(int value) {
            this.height = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="text">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="b" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="i" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="u" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="font" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="fontsize" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="fontcolor" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="xstart" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="ystart" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="xend" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="yend" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="linecolor" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="shape">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="point">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="totalpoints" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="fillcolor" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="linecolor" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="branch" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="audio">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="loop" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="image">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="urlname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="xstart" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="ystart" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="branch" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="video">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="loop" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="xstart" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="ystart" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="playtime" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="lastslide" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "text",
        "shape",
        "audio",
        "image",
        "video"
    })
    public static class Slide {

        @XmlElement(required = true)
        protected jaxbSlideshow.Slide.Text text;
        @XmlElement(required = true)
        protected jaxbSlideshow.Slide.Shape shape;
        @XmlElement(required = true)
        protected jaxbSlideshow.Slide.Audio audio;
        @XmlElement(required = true)
        protected jaxbSlideshow.Slide.Image image;
        @XmlElement(required = true)
        protected jaxbSlideshow.Slide.Video video;
        @XmlAttribute(name = "id")
        protected Integer id;
        @XmlAttribute(name = "duration")
        protected Integer duration;
        @XmlAttribute(name = "lastslide")
        protected Boolean lastslide;

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link jaxbSlideshow.Slide.Text }
         *     
         */
        public jaxbSlideshow.Slide.Text getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link jaxbSlideshow.Slide.Text }
         *     
         */
        public void setText(jaxbSlideshow.Slide.Text value) {
            this.text = value;
        }

        /**
         * Gets the value of the shape property.
         * 
         * @return
         *     possible object is
         *     {@link jaxbSlideshow.Slide.Shape }
         *     
         */
        public jaxbSlideshow.Slide.Shape getShape() {
            return shape;
        }

        /**
         * Sets the value of the shape property.
         * 
         * @param value
         *     allowed object is
         *     {@link jaxbSlideshow.Slide.Shape }
         *     
         */
        public void setShape(jaxbSlideshow.Slide.Shape value) {
            this.shape = value;
        }

        /**
         * Gets the value of the audio property.
         * 
         * @return
         *     possible object is
         *     {@link jaxbSlideshow.Slide.Audio }
         *     
         */
        public jaxbSlideshow.Slide.Audio getAudio() {
            return audio;
        }

        /**
         * Sets the value of the audio property.
         * 
         * @param value
         *     allowed object is
         *     {@link jaxbSlideshow.Slide.Audio }
         *     
         */
        public void setAudio(jaxbSlideshow.Slide.Audio value) {
            this.audio = value;
        }

        /**
         * Gets the value of the image property.
         * 
         * @return
         *     possible object is
         *     {@link jaxbSlideshow.Slide.Image }
         *     
         */
        public jaxbSlideshow.Slide.Image getImage() {
            return image;
        }

        /**
         * Sets the value of the image property.
         * 
         * @param value
         *     allowed object is
         *     {@link jaxbSlideshow.Slide.Image }
         *     
         */
        public void setImage(jaxbSlideshow.Slide.Image value) {
            this.image = value;
        }

        /**
         * Gets the value of the video property.
         * 
         * @return
         *     possible object is
         *     {@link jaxbSlideshow.Slide.Video }
         *     
         */
        public jaxbSlideshow.Slide.Video getVideo() {
            return video;
        }

        /**
         * Sets the value of the video property.
         * 
         * @param value
         *     allowed object is
         *     {@link jaxbSlideshow.Slide.Video }
         *     
         */
        public void setVideo(jaxbSlideshow.Slide.Video value) {
            this.video = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setId(Integer value) {
            this.id = value;
        }

        /**
         * Gets the value of the duration property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getDuration() {
            return duration;
        }

        /**
         * Sets the value of the duration property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setDuration(Integer value) {
            this.duration = value;
        }

        /**
         * Gets the value of the lastslide property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isLastslide() {
            return lastslide;
        }

        /**
         * Sets the value of the lastslide property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setLastslide(Boolean value) {
            this.lastslide = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="loop" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Audio {

            @XmlAttribute(name = "urlname")
            protected String urlname;
            @XmlAttribute(name = "starttime")
            protected Integer starttime;
            @XmlAttribute(name = "loop")
            protected Boolean loop;

            /**
             * Gets the value of the urlname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrlname() {
                return urlname;
            }

            /**
             * Sets the value of the urlname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrlname(String value) {
                this.urlname = value;
            }

            /**
             * Gets the value of the starttime property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getStarttime() {
                return starttime;
            }

            /**
             * Sets the value of the starttime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setStarttime(Integer value) {
                this.starttime = value;
            }

            /**
             * Gets the value of the loop property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isLoop() {
                return loop;
            }

            /**
             * Sets the value of the loop property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setLoop(Boolean value) {
                this.loop = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="urlname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="xstart" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="ystart" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="branch" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Image {

            @XmlAttribute(name = "urlname", required = true)
            protected String urlname;
            @XmlAttribute(name = "xstart", required = true)
            protected int xstart;
            @XmlAttribute(name = "ystart", required = true)
            protected int ystart;
            @XmlAttribute(name = "width")
            protected Integer width;
            @XmlAttribute(name = "height")
            protected Integer height;
            @XmlAttribute(name = "starttime")
            protected Integer starttime;
            @XmlAttribute(name = "duration")
            protected Integer duration;
            @XmlAttribute(name = "layer")
            protected Integer layer;
            @XmlAttribute(name = "branch")
            protected Integer branch;

            /**
             * Gets the value of the urlname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrlname() {
                return urlname;
            }

            /**
             * Sets the value of the urlname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrlname(String value) {
                this.urlname = value;
            }

            /**
             * Gets the value of the xstart property.
             * 
             */
            public int getXstart() {
                return xstart;
            }

            /**
             * Sets the value of the xstart property.
             * 
             */
            public void setXstart(int value) {
                this.xstart = value;
            }

            /**
             * Gets the value of the ystart property.
             * 
             */
            public int getYstart() {
                return ystart;
            }

            /**
             * Sets the value of the ystart property.
             * 
             */
            public void setYstart(int value) {
                this.ystart = value;
            }

            /**
             * Gets the value of the width property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setWidth(Integer value) {
                this.width = value;
            }

            /**
             * Gets the value of the height property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getHeight() {
                return height;
            }

            /**
             * Sets the value of the height property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setHeight(Integer value) {
                this.height = value;
            }

            /**
             * Gets the value of the starttime property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getStarttime() {
                return starttime;
            }

            /**
             * Sets the value of the starttime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setStarttime(Integer value) {
                this.starttime = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setDuration(Integer value) {
                this.duration = value;
            }

            /**
             * Gets the value of the layer property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getLayer() {
                return layer;
            }

            /**
             * Sets the value of the layer property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setLayer(Integer value) {
                this.layer = value;
            }

            /**
             * Gets the value of the branch property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBranch() {
                return branch;
            }

            /**
             * Sets the value of the branch property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBranch(Integer value) {
                this.branch = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="point">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="totalpoints" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="fillcolor" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="linecolor" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="branch" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "point"
        })
        public static class Shape {

            @XmlElement(required = true)
            protected jaxbSlideshow.Slide.Shape.Point point;
            @XmlAttribute(name = "totalpoints", required = true)
            protected int totalpoints;
            @XmlAttribute(name = "width", required = true)
            protected int width;
            @XmlAttribute(name = "height", required = true)
            protected int height;
            @XmlAttribute(name = "fillcolor")
            protected Integer fillcolor;
            @XmlAttribute(name = "starttime")
            protected Integer starttime;
            @XmlAttribute(name = "duration")
            protected Integer duration;
            @XmlAttribute(name = "layer")
            protected Integer layer;
            @XmlAttribute(name = "linecolor")
            protected String linecolor;
            @XmlAttribute(name = "branch")
            protected Integer branch;

            /**
             * Gets the value of the point property.
             * 
             * @return
             *     possible object is
             *     {@link jaxbSlideshow.Slide.Shape.Point }
             *     
             */
            public jaxbSlideshow.Slide.Shape.Point getPoint() {
                return point;
            }

            /**
             * Sets the value of the point property.
             * 
             * @param value
             *     allowed object is
             *     {@link jaxbSlideshow.Slide.Shape.Point }
             *     
             */
            public void setPoint(jaxbSlideshow.Slide.Shape.Point value) {
                this.point = value;
            }

            /**
             * Gets the value of the totalpoints property.
             * 
             */
            public int getTotalpoints() {
                return totalpoints;
            }

            /**
             * Sets the value of the totalpoints property.
             * 
             */
            public void setTotalpoints(int value) {
                this.totalpoints = value;
            }

            /**
             * Gets the value of the width property.
             * 
             */
            public int getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             */
            public void setWidth(int value) {
                this.width = value;
            }

            /**
             * Gets the value of the height property.
             * 
             */
            public int getHeight() {
                return height;
            }

            /**
             * Sets the value of the height property.
             * 
             */
            public void setHeight(int value) {
                this.height = value;
            }

            /**
             * Gets the value of the fillcolor property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getFillcolor() {
                return fillcolor;
            }

            /**
             * Sets the value of the fillcolor property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setFillcolor(Integer value) {
                this.fillcolor = value;
            }

            /**
             * Gets the value of the starttime property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getStarttime() {
                return starttime;
            }

            /**
             * Sets the value of the starttime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setStarttime(Integer value) {
                this.starttime = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setDuration(Integer value) {
                this.duration = value;
            }

            /**
             * Gets the value of the layer property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getLayer() {
                return layer;
            }

            /**
             * Sets the value of the layer property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setLayer(Integer value) {
                this.layer = value;
            }

            /**
             * Gets the value of the linecolor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLinecolor() {
                return linecolor;
            }

            /**
             * Sets the value of the linecolor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLinecolor(String value) {
                this.linecolor = value;
            }

            /**
             * Gets the value of the branch property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBranch() {
                return branch;
            }

            /**
             * Sets the value of the branch property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBranch(Integer value) {
                this.branch = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Point {

                @XmlAttribute(name = "x")
                protected Integer x;
                @XmlAttribute(name = "y")
                protected Integer y;
                @XmlAttribute(name = "num")
                protected Integer num;

                /**
                 * Gets the value of the x property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getX() {
                    return x;
                }

                /**
                 * Sets the value of the x property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setX(Integer value) {
                    this.x = value;
                }

                /**
                 * Gets the value of the y property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getY() {
                    return y;
                }

                /**
                 * Sets the value of the y property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setY(Integer value) {
                    this.y = value;
                }

                /**
                 * Gets the value of the num property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getNum() {
                    return num;
                }

                /**
                 * Sets the value of the num property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setNum(Integer value) {
                    this.num = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="b" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="i" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="u" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="font" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="fontsize" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="fontcolor" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="xstart" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="ystart" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="xend" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="yend" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="linecolor" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "b",
            "i",
            "u"
        })
        public static class Text {

            @XmlElement(required = true)
            protected String b;
            @XmlElement(required = true)
            protected String i;
            @XmlElement(required = true)
            protected String u;
            @XmlAttribute(name = "font")
            protected String font;
            @XmlAttribute(name = "fontsize")
            protected Integer fontsize;
            @XmlAttribute(name = "fontcolor")
            protected String fontcolor;
            @XmlAttribute(name = "starttime")
            protected Integer starttime;
            @XmlAttribute(name = "duration")
            protected Integer duration;
            @XmlAttribute(name = "layer")
            protected Integer layer;
            @XmlAttribute(name = "xstart", required = true)
            protected int xstart;
            @XmlAttribute(name = "ystart", required = true)
            protected int ystart;
            @XmlAttribute(name = "xend", required = true)
            protected int xend;
            @XmlAttribute(name = "yend", required = true)
            protected int yend;
            @XmlAttribute(name = "linecolor")
            protected String linecolor;

            /**
             * Gets the value of the b property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getB() {
                return b;
            }

            /**
             * Sets the value of the b property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setB(String value) {
                this.b = value;
            }

            /**
             * Gets the value of the i property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getI() {
                return i;
            }

            /**
             * Sets the value of the i property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setI(String value) {
                this.i = value;
            }

            /**
             * Gets the value of the u property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getU() {
                return u;
            }

            /**
             * Sets the value of the u property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setU(String value) {
                this.u = value;
            }

            /**
             * Gets the value of the font property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFont() {
                return font;
            }

            /**
             * Sets the value of the font property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFont(String value) {
                this.font = value;
            }

            /**
             * Gets the value of the fontsize property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getFontsize() {
                return fontsize;
            }

            /**
             * Sets the value of the fontsize property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setFontsize(Integer value) {
                this.fontsize = value;
            }

            /**
             * Gets the value of the fontcolor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFontcolor() {
                return fontcolor;
            }

            /**
             * Sets the value of the fontcolor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFontcolor(String value) {
                this.fontcolor = value;
            }

            /**
             * Gets the value of the starttime property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getStarttime() {
                return starttime;
            }

            /**
             * Sets the value of the starttime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setStarttime(Integer value) {
                this.starttime = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setDuration(Integer value) {
                this.duration = value;
            }

            /**
             * Gets the value of the layer property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getLayer() {
                return layer;
            }

            /**
             * Sets the value of the layer property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setLayer(Integer value) {
                this.layer = value;
            }

            /**
             * Gets the value of the xstart property.
             * 
             */
            public int getXstart() {
                return xstart;
            }

            /**
             * Sets the value of the xstart property.
             * 
             */
            public void setXstart(int value) {
                this.xstart = value;
            }

            /**
             * Gets the value of the ystart property.
             * 
             */
            public int getYstart() {
                return ystart;
            }

            /**
             * Sets the value of the ystart property.
             * 
             */
            public void setYstart(int value) {
                this.ystart = value;
            }

            /**
             * Gets the value of the xend property.
             * 
             */
            public int getXend() {
                return xend;
            }

            /**
             * Sets the value of the xend property.
             * 
             */
            public void setXend(int value) {
                this.xend = value;
            }

            /**
             * Gets the value of the yend property.
             * 
             */
            public int getYend() {
                return yend;
            }

            /**
             * Sets the value of the yend property.
             * 
             */
            public void setYend(int value) {
                this.yend = value;
            }

            /**
             * Gets the value of the linecolor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLinecolor() {
                return linecolor;
            }

            /**
             * Sets the value of the linecolor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLinecolor(String value) {
                this.linecolor = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="loop" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="xstart" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="ystart" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="layer" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="playtime" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Video {

            @XmlAttribute(name = "urlname")
            protected String urlname;
            @XmlAttribute(name = "starttime")
            protected Integer starttime;
            @XmlAttribute(name = "loop")
            protected Boolean loop;
            @XmlAttribute(name = "xstart")
            protected Integer xstart;
            @XmlAttribute(name = "ystart")
            protected Integer ystart;
            @XmlAttribute(name = "layer")
            protected Integer layer;
            @XmlAttribute(name = "playtime")
            protected Integer playtime;
            @XmlAttribute(name = "duration")
            protected Integer duration;

            /**
             * Gets the value of the urlname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrlname() {
                return urlname;
            }

            /**
             * Sets the value of the urlname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrlname(String value) {
                this.urlname = value;
            }

            /**
             * Gets the value of the starttime property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getStarttime() {
                return starttime;
            }

            /**
             * Sets the value of the starttime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setStarttime(Integer value) {
                this.starttime = value;
            }

            /**
             * Gets the value of the loop property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isLoop() {
                return loop;
            }

            /**
             * Sets the value of the loop property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setLoop(Boolean value) {
                this.loop = value;
            }

            /**
             * Gets the value of the xstart property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getXstart() {
                return xstart;
            }

            /**
             * Sets the value of the xstart property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setXstart(Integer value) {
                this.xstart = value;
            }

            /**
             * Gets the value of the ystart property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getYstart() {
                return ystart;
            }

            /**
             * Sets the value of the ystart property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setYstart(Integer value) {
                this.ystart = value;
            }

            /**
             * Gets the value of the layer property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getLayer() {
                return layer;
            }

            /**
             * Sets the value of the layer property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setLayer(Integer value) {
                this.layer = value;
            }

            /**
             * Gets the value of the playtime property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getPlaytime() {
                return playtime;
            }

            /**
             * Sets the value of the playtime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setPlaytime(Integer value) {
                this.playtime = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setDuration(Integer value) {
                this.duration = value;
            }

        }

    }

}
